### ISSUE TITLE
Import and export

### ISSUE THREAD

**Issue by EllipticEllipsis** [decompals/frogress#2]
- [ ] Ability to import CSVs
- [ ] Ability to export CSVs
- [x] Ability to import JSONs
- [x] Ability to export JSONs

**Comment by ethteck** [comment]
json exporting/importing is kinda done given that that's the main format of the api, so I'm gonna check those boxes. If you had a different idea for what this meant, though, lmk.

**Comment by ethteck** [comment]
Going to also close this, as I don't see a way to generically support CSVs without a complicated GUI or interactive cli program. I think the better path is to just educate people how to post to the db and help them write their own csv parser. Very few projects have legacy CSVs anyway, so this isn't something I see much value in spending a lot of time on, which I feel it would take to do well
