### ISSUE TITLE
Duplicate entries are allowed to be stored

### ISSUE THREAD

**Issue by Xeeynamo** [decompals/frogress#27]
During some testing in a local environment (thanks Docker!) I discovered it is possible to push an entry with the same `timestamp` and `git_hash` again and have both of them retrievable when fetching the metrics.

I do not personally think this should be the right behaviour. Ideally I would expect to see the new entry to replace the old one. As on what would be the primary key I would suggest to be the `git_hash` as that is the ultimate source of truth and it is salted with the timestamp as well.

**Comment by ethteck** [comment]
@laqieer yeah I don't disagree. This is an oversight, not intended behavior. I have a ton of plates spinning, so I can't guarantee when I'll get to this. But please feel free to submit a PR!

**Comment by ethteck** [comment]
Presumably multiple entries (from different versions, for example) could share the same git hash. But I think just having a unique constraint on git hash + a few other things would indeed be good. I'll try to work on this soon
