### ISSUE TITLE
Requests are blocked by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by laqieer** [decompals/frogress#31]
https://progress.deco.mp/data/fireemblem8/us/?mode=all
<img width="264" alt="截屏2023-04-20 21 17 46" src="https://user-images.githubusercontent.com/8841957/233378346-6ae2d8f1-4e86-4730-af1b-75c36b009864.png">
https://angheloalf.github.io/drmario64/
<img width="1406" alt="截屏2023-04-20 21 18 47" src="https://user-images.githubusercontent.com/8841957/233378592-89feb037-7106-4199-b118-ef2de59199a5.png">
https://laqieer.github.io/fe-decomp-portal/
<img width="656" alt="image" src="https://user-images.githubusercontent.com/8841957/233379299-da32581a-db3c-409b-9040-aa93275194f8.png">

**Comment by ethteck** [comment]
Sorry about that! Rebooted the containers and it seems to be alright now
