### ISSUE TITLE
api_key request

### ISSUE THREAD

**Issue by MokhaLeee** [decompals/frogress#37]
Hello ethteck, since we haven't been able to reach StanH, so we forked a [new repository](https://github.com/FireEmblemUniverse/fireemblem6j) to continue the FE6 decomp project. I'm currently the maintainer of the new repository. I hope you can PM me the FE6 API key to replace the one from the original repository, thanks!

cc @laqieer

**Comment by ethteck** [comment]
Hey - I'm happy to give you the key, but just to make sure, did you try emailing them too? I see both discord and email as contact points on their profile:
> discord: nat_776
email: deindall AT outlook DOT com

**Comment by MokhaLeee** [comment]
Thank you for the reminder! Previously, everyone was unable to contact StanH via GitHub and Discord, I may try to reach out to him through email.

**Comment by ethteck** [comment]
gotcha! okay, let's give it like a day or two, and if you don't hear back, I'll send the key

**Comment by MokhaLeee** [comment]
sad, no reply :(

**Comment by ethteck** [comment]
mawhp. okay

**Comment by ethteck** [comment]
do you have discord?

**Comment by MokhaLeee** [comment]
Yes, you can contact me via mokha.li (or Mokha#8860?)
![image](https://github.com/user-attachments/assets/55dd22c2-4fb1-412d-b399-7882bd7ffb60)

**Comment by ethteck** [comment]
Reached out there. thanks :) closing this for now
